name = "Asgard"
author = "Millennium"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1811d552d55e86fb072dd5770a08dacbc774260ca2848d80e37467c507d0e75"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
