name = "Asgard"
author = "Millennium"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b97ce099b427e08040e997479fbfa92d32e72c1f5625d0f3b9033e6f57f1884"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
