name = "Asgard"
author = "Millennium"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44cc1ab3710ea3e211235584cd7c019c2f5dc3339b726be01ee76befc432ff77"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
